### ISSUE TITLE
Version 0.0.7 error but version 0.0.6 runs fine

### ISSUE THREAD

**Issue by perez987** [USBToolBox/tool#10]
My system: Z390 Aorus Elite + Big Sur 11.3.1. I've tried 0.0.6 version of the tool and it runs fine but 0.0.7 version shows in Terminal at discovering ports:

Getting controllers...
Traceback (most recent call last):
  File "macOS.py", line 174, in <module>
  File "base.py", line 50, in __init__
  File "base.py", line 680, in monu
  File "utils.py", line 204, in start
  File "utils.py", line 188, in select
  File "base.py", line 222, in discover_ports
  File "macOS.py", line 125, in get_controllers
  File "base.py", line 114, in merge_controllers
  File "base.py", line 130, in merge_ports
  File "base.py", line 156, in merge_devices
IndexError: list index out of range
[1499] Failed to execute script macOS

Thank you for your work. I have a USBMap fully functional made with your tool.

**Comment by perez987** [comment]
I answer to myself. I have to delete the usb.json and settings.json files generated by the previous version. This fixes the error.
