### ISSUE TITLE
Not works On Windows 11 (release 21H2)  and Laptop MSI Bravo B5DD

### ISSUE THREAD

**Issue by HiPSOW** [USBToolBox/tool#29]
Testing with latest version avaible: 0.0.9

**Describe the bug**
Running Windows.exe on my laptop in a administrator cmd window results in:

  #######################################################
 #                  USBToolBox 0.0.9                   #
#######################################################

Saved Data: None

D.  Discover Ports
S.  Select Ports and Build Kext
C.  Change Settings
Q.  Quit

Select an option: D

  #######################################################
 #                  Port Discovery                     #
#######################################################

Getting controllers...
Traceback (most recent call last):
  File "Windows.py", line 149, in <module>
  File "Windows.py", line 32, in __init__
  File "base.py", line 49, in __init__
  File "base.py", line 679, in monu
  File "utils.py", line 204, in start
  File "utils.py", line 188, in select
  File "base.py", line 221, in discover_ports
  File "Windows.py", line 111, in get_controllers
  File "Windows.py", line 35, in update_usbdump
  File "usbdump.py", line 228, in get_controllers
  File "usbdump.py", line 145, in serialize_hub
TypeError: 'NoneType' object is not iterable
[1280] Failed to execute script Windows

C:\Data\Install\Platform\OS\Mac_OS\Tools\USB_ToolBox\RELEASES\0.0.9>

**Debugging information attached**

**Hardware:**
 - Motherboard  /Laptop : MSI Bravo 15, Model B5DD (CPU Ryzen 5800H and GPU Radeon RX-5500M)
 - OS: Windows 11 Release 2H21

**Additional context**
Executed on cmd (user) and cmd with adminitrative permissions. with usb 3 attached in a port or,with none usb attached, same error.
[Windows11_debug.zip](https://github.com/USBToolBox/tool/files/7757031/Windows11_debug.zip)

**Comment by HiPSOW** [comment]
I have noMachine software that mounts a virtual USBs , when i go to device manager and disable this virtual usb ports, the error change to:

  #######################################################
 #                  USBToolBox 0.0.9                   #
#######################################################

Saved Data: None

D.  Discover Ports
S.  Select Ports and Build Kext
C.  Change Settings
Q.  Quit

Select an option: D
  #######################################################
 #                  Port Discovery                     #
#######################################################


Getting controllers...
Traceback (most recent call last):
  File "Windows.py", line 149, in <module>
  File "Windows.py", line 32, in __init__
  File "base.py", line 49, in __init__
  File "base.py", line 679, in monu
  File "utils.py", line 204, in start
  File "utils.py", line 188, in select
  File "base.py", line 221, in discover_ports
  File "Windows.py", line 111, in get_controllers
  File "Windows.py", line 35, in update_usbdump
  File "usbdump.py", line 212, in get_controllers
  File "json\__init__.py", line 346, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[14300] Failed to execute script Windows

C:\Data\Install\Platform\OS\Mac_OS\Tools\USB_ToolBox\RELEASES\0.0.9>

C:\Data\Install\Platform\OS\Mac_OS\Tools\USB_ToolBox\RELEASES\0.0.9>debug_dump.exe
Traceback (most recent call last):
  File "debug_dump.py", line 82, in <module>
  File "json\__init__.py", line 346, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[8176] Failed to execute script debug_dump

C:\Data\Install\Platform\OS\Mac_OS\Tools\USB_ToolBox\RELEASES\0.0.9>


![image](https://user-images.githubusercontent.com/34518065/146979755-ca37bf46-d5d6-4c0b-a3fa-5e3b6de3bd2e.png)

**Comment by dhinakg** [comment]
Yea, I can reproduce this on my local machine too. Working on it.

**Comment by dhinakg** [comment]
Please test with [0.1.0](https://github.com/USBToolBox/tool/releases/tag/0.1.0), it should fix your issue
