### ISSUE TITLE
AsRock X99 WS-E10G/10G "KeyError: 'show_friendly_types'"

### ISSUE THREAD

**Issue by robotogre** [USBToolBox/tool#38]
Latest release from https://github.com/USBToolBox/tool/releases.

**Describe the bug**
Run ./Windows.exe from Windows Terminal. Select 'D'. Output:

`  #######################################################
 #                  Port Discovery                     #
#######################################################

Intel(R) C610 series/X99 chipset USB Enhanced Host Controller #2 - 8D2D | USB 2.0 (EHCI) | 2 ports
Traceback (most recent call last):
  File "Windows.py", line 160, in <module>
  File "Windows.py", line 43, in __init__
  File "base.py", line 49, in __init__
  File "base.py", line 696, in monu
  File "utils.py", line 204, in start
  File "utils.py", line 188, in select
  File "base.py", line 232, in discover_ports
  File "base.py", line 189, in print_controllers
  File "base.py", line 170, in port_to_str
KeyError: 'show_friendly_types'
[17132] Failed to execute script 'Windows' due to unhandled exception!
C:\Users\tomsh\Downloads>`

**Debugging information**
If on Windows, please download debug_dump from https://github.com/USBToolBox/tool/releases. It will save a file with debugging information, please upload it to this bug report.

**Hardware:**
 - ASRock X99 WS-E10G
 - OS: Windows 10 Pro - Version 10.0.19043 Build 19043
 - 
 DEBUG DUMP:
[x99.zip](https://github.com/USBToolBox/tool/files/8835371/x99.zip)

**Comment by dhinakg** [comment]
Please delete settings.json and rerun the program, I'm working on better settings handling but for now that'll fix it.
