### ISSUE TITLE
pywintypes.com_error: (-2147352567, '发生意外。', (0, 'SWbemObjectEx', '无效的参数 ', None, 0, -2147217400), None)

### ISSUE THREAD

**Issue by chunde743001734** [USBToolBox/tool#46]
![M 3HCJ0}97M1818R%CR%DWK](https://user-images.githubusercontent.com/110798002/190884360-cba70b4c-ffb0-4e70-8992-e09bd515fa49.png)

**Comment by chunde743001734** [comment]
这是什么原因？

**Comment by dhinakg** [comment]
Hi, can you reproduce this reliably?

**Comment by chunde743001734** [comment]
Windows.exe这个文件吗?这个文件可以复制啊

**Comment by startergo** [comment]
I got similar error:
```
Traceback (most recent call last):
  File "Windows.py", line 160, in <module>
  File "Windows.py", line 43, in __init__
  File "base.py", line 47, in __init__
  File "json\__init__.py", line 293, in load
  File "json\__init__.py", line 346, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[6784] Failed to execute script 'Windows' due to unhandled exception!
```
What is strange though it did not error initially. After I opened once USBTreeView it started consistently failing.

**Comment by dhinakg** [comment]
That is a completely different error in different code, please open a new issue

**Comment by dhinakg** [comment]
@chunde743001734 can you upload debug information? Run debug_dump.exe from the latest release

**Comment by dhinakg** [comment]
Please reopen if you can reproduce
