### ISSUE TITLE
Crashes on Getting Controllers...

### ISSUE THREAD

**Issue by M0HID** [USBToolBox/tool#55]
Tried latest, tried v0.1.0 as said in #27 always crashes with the below error

```
  #######################################################
 #                  Port Discovery                     #
#######################################################


Getting controllers...
Traceback (most recent call last):
  File "Windows.py", line 160, in <module>
  File "Windows.py", line 43, in __init__
  File "base.py", line 49, in __init__
  File "base.py", line 696, in monu
  File "utils.py", line 204, in start
  File "utils.py", line 188, in select
  File "base.py", line 221, in discover_ports
  File "Windows.py", line 122, in get_controllers
  File "Windows.py", line 46, in update_usbdump
  File "usbdump.py", line 215, in get_controllers
  File "json\__init__.py", line 346, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[11540] Failed to execute script 'Windows' due to unhandled exception!

```

intel i5 6500
python latest ver 3.11

**Comment by dhinakg** [comment]
Please try https://github.com/USBToolBox/tool/suites/13506490682/artifacts/742155906

**Comment by vxibrahim** [comment]
I'm having this issue too and the link you've replied with doesn't work either

**Comment by Svito4** [comment]
After unplugging all devices, disabling Bluetooth, downloading version 2.0 as a zip file, extracting it, and launching it, it finally worked for me.

**Comment by dhinakg** [comment]
If you're still having trouble, please open a new issue and make sure you include the debug dump.
