### ISSUE TITLE
USBtool is'nt geberating kexts

### ISSUE THREAD

**Issue by vector-co-uz** [USBToolBox/tool#58]
**I'm using latest version of this tool.**
The program just closes and does not create any file. Windows 11  22H2.
Tried also test build from issues section.

[usb.zip](https://github.com/USBToolBox/tool/files/11745605/usb.zip)

**Comment by dhinakg** [comment]
Please run the tool from the command line and see if it prints out any errors

**Comment by paytondevs** [comment]
im having the same issue. here's output upon trying to build kext:
```
Generating Info.plist...
Traceback (most recent call last):
  File "Windows.py", line 160, in <module>
  File "Windows.py", line 43, in __init__
  File "base.py", line 49, in __init__
  File "base.py", line 696, in monu
  File "utils.py", line 204, in start
  File "utils.py", line 188, in select
  File "base.py", line 370, in select_ports
  File "base.py", line 581, in build_kext
  File "base.py", line 508, in choose_matching_key
RuntimeError: No matching key available
[16528] Failed to execute script 'Windows' due to unhandled exception!
```

**Comment by dhinakg** [comment]
Huh, that's a really rare edge case...

Can you upload a debug dump?

**Comment by paytondevs** [comment]
how would i do that?

**Comment by dhinakg** [comment]
Run debug_dump.exe from the releases tab, the same place where you downloaded USBToolBox

**Comment by paytondevs** [comment]
sorry for the late response! here's the dump:
[dump.zip](https://github.com/USBToolBox/tool/files/11780035/dump.zip)

**Comment by vector-co-uz** [comment]
> Please run the tool from the command line and see if it prints out any errors

```
Generating Info.plist...
Traceback (most recent call last):
  File "Windows.py", line 160, in <module>
  File "Windows.py", line 43, in __init__
  File "base.py", line 49, in __init__
  File "base.py", line 696, in monu
  File "utils.py", line 204, in start
  File "utils.py", line 188, in select
  File "base.py", line 370, in select_ports
  File "base.py", line 581, in build_kext
  File "base.py", line 508, in choose_matching_key
RuntimeError: No matching key available
[12552] Failed to execute script 'Windows' due to unhandled exception!
PS D:\Programmalar\MacOS\Opencore\dist>
```

**Comment by dhinakg** [comment]
I can't seem to reproduce this - it works on my end. Could you please additionally upload `usb.json`?

**Comment by vector-co-uz** [comment]
[usb.zip](https://github.com/USBToolBox/tool/files/11990349/usb.zip)

**Comment by Qu1dAg1s** [comment]
Using USBtoolBox version 0.2. Same problem. No Kext. It creates UTBMap.kext folder, subfolder Contents and file Info.plist inside. That´s all. No UTBMap.kext.

UPDATE: The line below is from OpenCore Install Guide (Bold is mine):

**_Windows and Linux note: Kexts will look like normal folders in your OS, double check that the folder you are installing has a .kext extension visible(and do not add one manually if it's missing)._**

**Comment by bugz8unny69** [comment]
I just ran into the same issue myself trying to USB map on my end. Here's the information requested.

[debug_dump.zip](https://github.com/USBToolBox/tool/files/12179251/debug_dump.zip)

**Comment by parknich** [comment]
I am also getting the exact same error.
[debugdump.json](https://github.com/USBToolBox/tool/files/13197786/debugdump.json)

**Comment by parknich** [comment]
> Run debug_dump.exe from the releases tab, the same place where you downloaded USBToolBox

Do you know why this is happening?

**Comment by Fulka50** [comment]
If you have Parsec uninstall the usb drivers. They cannot be build.

**Comment by Sothlord** [comment]
Same Issue
[Dump.json](https://github.com/user-attachments/files/25402736/Dump.json)
